**1. Install the libraries required to import the model from Hugging face**

In [1]:
!pip install torch transformers datasets peft accelerate rouge-score evaluate pandas

Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cpu)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.18.1)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Collecting rouge-score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.10.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from peft) (5.9.5)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge-score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge-score) (3.9.1)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge-score) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.2.25)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (8.3.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (1.5.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 2.4 MB/s eta 0:00:00
Building wheels for collected packages: rouge-score
  Building wheel for rouge-score (setup.py) ... done
  Created wheel for rouge-score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=278756eabc6de48fe4e9a25999fb5a4f02473ea16dd2c8dc8f920390eb9ffe03
  Stored in directory: /root/.cache/pip/wheels/85/9d/af/01feefbe7d55ef5468796f0c68225b6788e85d9d0a281e7a70
Successfully built rouge-score
Installing collected packages: rouge-score, evaluate
Successfully installed evaluate-0.4.6 rouge-score-0.1.2

**2. Read the data after the data is cleaned and stored in a csv file**

In [2]:
import pandas as pd
df = pd.read_csv('/content/sample_data/output_20260415064406.csv')
df.head()

,id,findings,labels
0,3997,"Heart size within normal limits. Small, nodula...","No acute findings, no evidence for active TB."
1,3996,The lungs are clear. Heart size is normal. No ...,Clear lungs. No acute cardiopulmonary abnormal...
2,3995,The cardiomediastinal silhouette and pulmonary...,1. Interval resolution of bibasilar airspace d...
3,3994,Similar mild cardiomegaly. Of the pulmonary va...,Mild cardiomegaly with XXXX of early failure.
4,3993,The heart is mildly enlarged. Left hemidiaphra...,Borderline cardiomegaly without acute disease.

**3. Include additional text in the findings column which will summarize the text.**

In [3]:
df["findings"] = "summarize medical report and return summary in no more than 2 sentences: " + df["findings"]

In [4]:
df.head()
print(df['findings'][0])

summarize medical report and return summary in no more than 2 sentences: Heart size within normal limits. Small, nodular opacity in the right upper lobe. This does not look like an acute infiltrate, and more XXXX represents a granuloma. No pneumothorax or effusions.

**4. Download the model from huggingface**

In [5]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = "google/flan-t5-small"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/308M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/190 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

**5. Use Lora to train the model**

In [6]:
from peft import LoraConfig, get_peft_model

lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["q", "v"],
    lora_dropout=0.1,
    bias="none",
    task_type="SEQ_2_SEQ_LM"
)

model = get_peft_model(model, lora_config)

WARNING:torchao.kernel.intmm:Warning: Detected no triton, on systems without Triton certain kernels will not work

**6. Set the training arguments**

In [7]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./medical_model",
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    num_train_epochs=3,
    learning_rate=2e-4,
    logging_steps=100,
    eval_strategy="epoch",
    save_strategy="epoch"
)

In [8]:
df.columns

Index(['id', 'findings', 'labels'], dtype='object')

**7. Split the data into train and test**

In [9]:
from transformers import Trainer
from datasets import Dataset
from sklearn.model_selection import train_test_split

# Convert pandas DataFrame to Hugging Face Dataset
dataset = Dataset.from_pandas(df)

# Split the dataset into train and test sets using the Dataset's own split method
split_datasets = dataset.train_test_split(test_size=0.1, seed=42)
train_dataset = split_datasets["train"]
test_dataset = split_datasets["test"]

**8. Tokenize the data**

In [12]:
# Define the tokenization function
def tokenize_function(examples):
  # return tokenizer(examples["findings"],
  #                  text_target=examples["labels"],
  #                  truncation=True)
  return tokenizer(
        [str(f) for f in examples["findings"]],
        text_target=[str(l) for l in examples["labels"]],
        truncation=True
    )

# Apply tokenization to the datasets
tokenized_train_dataset = train_dataset.map(tokenize_function, batched=True)
tokenized_test_dataset = test_dataset.map(tokenize_function, batched=True)

# Remove the original text columns as they are no longer needed
tokenized_train_dataset = tokenized_train_dataset.remove_columns(["id", "findings"])
tokenized_test_dataset = tokenized_test_dataset.remove_columns(["id", "findings"])

# Make sure the 'labels' column is correctly set for training
tokenized_train_dataset.set_format("torch", columns=["input_ids", "attention_mask", "labels"])
tokenized_test_dataset.set_format("torch", columns=["input_ids", "attention_mask", "labels"])

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train_dataset,
    eval_dataset=tokenized_test_dataset
)

trainer.train()

Map:   0%|          | 0/1525 [00:00<?, ? examples/s]

Map:   0%|          | 0/170 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

TrainOutput(global_step=4575, training_loss=8.391514672451333, metrics={'train_runtime': 2125.101, 'train_samples_per_second': 2.153, 'train_steps_per_second': 2.153, 'total_flos': 124407333586944.0, 'train_loss': 8.391514672451333, 'epoch': 3.0})

**9. Save the model**

In [13]:
import os

output_dir = "/content/medical_model/final-artifacts-g5/medical_summarizer_model_g5"
os.makedirs(output_dir, exist_ok=True)

merged_model = trainer.model.merge_and_unload()
merged_model.save_pretrained(output_dir)
tokenizer.save_pretrained(output_dir)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('/content/medical_model/final-artifacts-g5/medical_summarizer_model_g5/tokenizer_config.json',
 '/content/medical_model/final-artifacts-g5/medical_summarizer_model_g5/tokenizer.json')

**10. Run predictions**

In [14]:
import pandas as pd
import torch
import evaluate
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# load model
model_path = "/content/medical_model/final-artifacts-g5/medical_summarizer_model_g5"
tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForSeq2SeqLM.from_pretrained(model_path)

device = torch.device("cpu")
model.to(device)

# load data
test_df = pd.read_csv("/content/sample_data/output_validation_20260415071239.csv")

inputs = test_df["findings"].tolist()
references = test_df["labels"].tolist()

# predict
predictions = []

for text in inputs:

    text = "summarize medical report and return summary in no more than 2 sentences: " + text

    tokens = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=256
    ).to(device)

    output = model.generate(
        **tokens,
        max_length=64,
        num_beams=4
    )

    pred = tokenizer.decode(
        output[0],
        skip_special_tokens=True
    )

    predictions.append(pred)

print(predictions)
# rouge
rouge = evaluate.load("rouge")

results = rouge.compute(
    predictions=predictions,
    references=references
)

print(results)

Loading weights:   0%|          | 0/190 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

['No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary abnormality.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary d

Downloading builder script: 0.00B [00:00, ?B/s]

{'rouge1': np.float64(0.47109690237365653), 'rouge2': np.float64(0.3210758829601464), 'rougeL': np.float64(0.47031940910395825), 'rougeLsum': np.float64(0.47072452458306135)}

In [17]:
import zipfile
import os
from google.colab import files

folder_to_compress = "/content/medical_model/final-artifacts-g5/medical_summarizer_model_g5"
output_zip_name = "medical_summarizer_model_g5.zip"

# Create a ZipFile object
with zipfile.ZipFile(output_zip_name, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for root, dirs, files_in_folder in os.walk(folder_to_compress):
        for file in files_in_folder:
            file_path = os.path.join(root, file)
            # Add file to zip, preserving directory structure relative to folder_to_compress
            zipf.write(file_path, os.path.relpath(file_path, folder_to_compress))

print(f"'{folder_to_compress}' successfully compressed to '{output_zip_name}'")

# Download the zip file
files.download(output_zip_name)

'/content/medical_model/final-artifacts-g5/medical_summarizer_model_g5' successfully compressed to 'medical_summarizer_model_g5.zip'